import{S as d,i as l}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function u(i){const s="https://pixabay.com/api/?"+new URLSearchParams({key:"44502992-491f023f405adfa93e793762c",q:i,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(s).then(o=>{if(!o.ok)throw new Error(o.status);return o.json()})}const f=new d(".gallery a",{captionsData:"alt",captionDelay:250});function m(i,r){r.innerHTML=p(i),f.refresh()}function p(i){return i.hits.map(({webformatURL:r,largeImageURL:s,tags:o,likes:e,views:t,comments:n,downloads:c})=>`<li>
                <a href="${s}"><img src='${r}' alt='${o}'></a>
                <div class="content">
                    <div class="item"><h3>Likes</h3><p>${e}</p></div>
                    <div class="item"><h3>Views</h3><p>${t}</p></div>
                    <div class="item"><h3>Comments</h3><p>${n}</p></div>
                    <div class="item"><h3>Downloads</h3><p>${c}</p></div>
                </div>
            </li>`).join("")}const a={form:document.querySelector("#form-request"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")};a.form.addEventListener("submit",i=>{i.preventDefault(),a.loader.classList.remove("hidden");const r=i.target.query.value.trim();if(!r){a.loader.classList.add("hidden"),l.warning({title:"Attention!",message:"Search field must be filled",messageSize:"16",position:"topRight",close:!1,displayMode:1});return}u(r).then(s=>{if(!s.totalHits)throw a.gallery.innerHTML="",new Error("Sorry, there are no images matching your search query. Please try again!");m(s,a.gallery)}).catch(s=>{l.error({title:"Error!",message:s.message,messageSize:"16",position:"topRight",close:!1,displayMode:1})}).finally(()=>{a.loader.classList.add("hidden")}),i.target.reset()});
//# sourceMappingURL=commonHelpers.js.map
