import{S as u,i as l}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const c=new URLSearchParams({key:"44502992-491f023f405adfa93e793762c",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0});function f(o){return fetch(o).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}const m=new u(".gallery a",{captionsData:"alt",captionDelay:250});function h(o,t){t.innerHTML=p(o),m.refresh()}function p(o){return o.hits.map(({webformatURL:t,largeImageURL:i,tags:s,likes:e,views:r,comments:a,downloads:d})=>`<li>
                <a href="${i}"><img src='${t}' alt='${s}'></a>
                <div class="content">
                    <div class="item"><h3>Likes</h3><p>${e}</p></div>
                    <div class="item"><h3>Views</h3><p>${r}</p></div>
                    <div class="item"><h3>Comments</h3><p>${a}</p></div>
                    <div class="item"><h3>Downloads</h3><p>${d}</p></div>
                </div>
            </li>`).join("")}const n={form:document.querySelector("#form-request"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")};n.form.addEventListener("submit",o=>{o.preventDefault(),n.loader.classList.remove("hidden");const t=o.target.query.value.trim();setTimeout(()=>{if(!t){n.loader.classList.add("hidden"),l.warning({title:"Attention!",message:"Search field must be filled",messageSize:"16",position:"topRight",close:!1,displayMode:1});return}c.set("q",t);const i="https://pixabay.com/api/?"+c;f(i).then(s=>{if(console.log(s),!s.totalHits)throw new Error("Sorry, there are no images matching your search query. Please try again!");h(s,n.gallery)}).catch(s=>{l.error({title:"Error!",message:s.message,messageSize:"16",position:"topRight",close:!1,displayMode:1})}),o.target.reset(),n.loader.classList.add("hidden")},1e3)});
//# sourceMappingURL=commonHelpers.js.map
